version: '3.1'

services:
  nginx:
    image: nginx:1.23.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    ports:
      - "80:80"
      - "443:443"

  certbot:
    ports:
      - "6000:80"
    env_file:
      - .env
    volumes:
      - ./nginx/:/etc/nginx/
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}

  image-server:
    build: image-service/image-server
    image: image-server
    container_name: image-server
    env_file: .env
    ports:
      - "9090:9090"
    environment:
      - OPENAI_SECRET_KEY=${OPENAI_SECRET_KEY}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}

  main-service:
    build: main-service
    image: main-service
    container_name: main-service
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - coverit-db
      - image-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://coverit-db:5432/coverit
      - SPRING_DATASOURCE_USER=${SPRING_DATASOURCE_USER}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - TOKEN_SIGNING_KEY=${TOKEN_SIGNING_KEY}

  coverit-db:
    image: postgres:14-alpine
    container_name: postgres-coverit
    env_file: .env
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=coverit
      - POSTGRES_USER=${SPRING_DATASOURCE_USER}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

  rabbitmq:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: rabbitmq
    env_file:
      - .env
    environment:
      TZ: Europe/Berlin
      RABBITMQ_DEFAULT_USER: ${SPRING_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${SPRING_RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"