-- Users Table
CREATE TABLE IF NOT EXISTS users
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hifi_release_generations  BIGINT,
    lofi_release_generations  BIGINT,
    hifi_playlist_generations BIGINT,
    lofi_playlist_generations BIGINT,
    email                     VARCHAR(254),
    username                  VARCHAR(250),
    password                  VARCHAR,
    verification_code         VARCHAR(64),
    patron_name               VARCHAR(64),
    is_enabled                BOOLEAN NOT NULL,
    is_subscribed             BOOLEAN NOT NULL,
    enabled_at                TIMESTAMP WITHOUT TIME ZONE,
    subscribed_at             TIMESTAMP WITHOUT TIME ZONE
);

-- Track Table
CREATE TABLE IF NOT EXISTS track
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    authors VARCHAR      NOT NULL,
    title   VARCHAR(200) NOT NULL
);

-- Cover Table
CREATE TABLE IF NOT EXISTS cover
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    vibe        VARCHAR(100),
    link        VARCHAR(1000) NOT NULL,
    prompt      VARCHAR(1000) NOT NULL,
    is_abstract BOOLEAN,
    is_lofi     BOOLEAN       NOT NULL,
    is_saved    BOOLEAN       NOT NULL,
    cover_type  VARCHAR(31)   NOT NULL
);

-- Playlist Table
CREATE TABLE IF NOT EXISTS playlist
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                 VARCHAR(200) NOT NULL,
    vibe                  VARCHAR(100),
    url                   VARCHAR(400) NOT NULL,
    is_private            BOOLEAN,
    is_saved              BOOLEAN,
    user_id               BIGINT,
    hifi_generations_left BIGINT,
    lofi_generations_left BIGINT,
    saved_at              TIMESTAMP WITHOUT TIME ZONE,
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Playlist Track Table
CREATE TABLE IF NOT EXISTS playlist_track
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT,
    track_id    BIGINT,
    FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE,
    FOREIGN KEY (track_id) REFERENCES track (id)
);

-- Playlist Cover Table
CREATE TABLE IF NOT EXISTS playlist_cover
(
    playlist_id BIGINT,
    cover_id    BIGINT,
    PRIMARY KEY (playlist_id, cover_id),
    FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE,
    FOREIGN KEY (cover_id) REFERENCES cover (id)
);

-- Likes Table
CREATE TABLE IF NOT EXISTS likes
(
    user_id     BIGINT,
    playlist_id BIGINT,
    PRIMARY KEY (user_id, playlist_id),
    FOREIGN KEY (user_id) REFERENCES users (id),
    FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE
);

-- Release Table
CREATE TABLE IF NOT EXISTS release
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(50),
    user_id    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    is_saved   BOOLEAN,
    saved_at   TIMESTAMP WITHOUT TIME ZONE,
    FOREIGN KEY (user_id) REFERENCES users (id)
);

-- Release Cover Table with additional fields for mood and description
CREATE TABLE IF NOT EXISTS release_cover
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    release_id       BIGINT,
    cover_id         BIGINT,
    object           VARCHAR(60),
    surrounding      VARCHAR(60),
    mood             TEXT,
    coverDescription TEXT,
    FOREIGN KEY (release_id) REFERENCES release (id),
    FOREIGN KEY (cover_id) REFERENCES cover (id)
);
