INSERT INTO users (email, username, password, is_enabled, is_subscribed)
VALUES ('user1@example.com', 'user1', 'password1', true, false),
       ('user2@example.com', 'user2', 'password2', true, false),
       ('user3@example.com', 'user3', 'password3', true, false),
       ('user4@example.com', 'user4', 'password4', true, false),
       ('user5@example.com', 'user5', 'password5', true, false),
       ('user6@example.com', 'user6', 'password6', true, false),
       ('user7@example.com', 'user7', 'password7', true, false),
       ('user8@example.com', 'user8', 'password8', true, false),
       ('user9@example.com', 'user9', 'password9', true, false),
       ('user10@example.com', 'user10', 'password10', true, false);

INSERT INTO playlist (title, vibe, url, is_private, is_saved, user_id, cover_id, hifi_generations_left,
                      lofi_generations_left, saved_at, created_at)
VALUES ('playlist 1', 'ENDLESS_JOY', 'https://open.spotify.com/playlist/5eamAjsBHoXLEL9x64ttBu?si=874909480b1a46b6',
        false, true, 1, 3, 0, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('playlist 2', 'DANCING_FLOOR', 'https://open.spotify.com/playlist/5eamAjsBHoXLEL9x64ttBu?si=874909480b1a46b6',
        true, false, 2, 5, 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('playlist 3', 'NATURE_DOES_NOT_CARE',
        'https://open.spotify.com/playlist/5eamAjsBHoXLEL9x64ttBu?si=874909480b1a46b6', false, true, 3, 7, 1, 0,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('playlist 4', 'BREAKING_DOWN', 'https://open.spotify.com/playlist/5eamAjsBHoXLEL9x64ttBu?si=874909480b1a46b6',
        true, false, 4, 9, 0, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('playlist 5', 'CAMPFIRE_CALMNESS',
        'https://open.spotify.com/playlist/5eamAjsBHoXLEL9x64ttBu?si=874909480b1a46b6', false, true, 5, 11, 1, 2,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('playlist 6', 'TOUGH_AND_STRAIGHT',
        'https://open.spotify.com/playlist/5eamAjsBHoXLEL9x64ttBu?si=874909480b1a46b6', true, false, 6, 13, 1, 0,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('playlist 7', 'ENDLESS_JOY', 'https://open.spotify.com/playlist/5eamAjsBHoXLEL9x64ttBu?si=874909480b1a46b6',
        false, true, 7, 15, 0, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('playlist 8', 'DANCING_FLOOR', 'https://open.spotify.com/playlist/5eamAjsBHoXLEL9x64ttBu?si=874909480b1a46b6',
        true, false, 8, 17, 2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('playlist 9', 'NATURE_DOES_NOT_CARE',
        'https://open.spotify.com/playlist/5eamAjsBHoXLEL9x64ttBu?si=874909480b1a46b6', false, true, 9, 19, 0, 2,
        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('playlist 10', 'BREAKING_DOWN', 'https://open.spotify.com/playlist/5eamAjsBHoXLEL9x64ttBu?si=874909480b1a46b6',
        true, false, 10, 21, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);