INSERT INTO cover (cover_type, created_at, link, prompt, is_abstract, is_lofi, is_saved)
VALUES ('PLAYLIST_COVER', CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true, false),
       ('PLAYLIST_COVER', CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true, false),
       ('PLAYLIST_COVER', CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true, false),
       ('PLAYLIST_COVER', CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true, false),
       ('PLAYLIST_COVER', CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true, false),
       ('PLAYLIST_COVER', CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true, false),
       ('PLAYLIST_COVER', CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true, false),
       ('PLAYLIST_COVER', CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt for DALLE: An image depicting: A golden voyage through multicolored skies, where light and shade dance among the constellation dust. The landscape shows floating duvet over tropic waters, surrounded by murmuration of warm dappled light. The picture should include natural landscape, be organic, fantasy',
        false, true, false),
       ('PLAYLIST_COVER', CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true, false),
       ('PLAYLIST_COVER', CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true, false),
       ('PLAYLIST_COVER', CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true, false);