INSERT INTO cover (created_at, link, prompt, is_abstract, is_lofi)
VALUES (CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true),
       (CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true),
       (CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true),
       (CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true),
       (CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true),
       (CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true),
       (CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true),
       (CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true),
       (CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true),
       (CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true),
       (CURRENT_TIMESTAMP, 'https://res.cloudinary.com/dsfopuxjf/image/upload/v1714059426/srm7mhfivkluwdz44k1n.png', 'prompt',
        false, true);